## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [1]:
import numpy as np
a= np.array(list(map(int,input().split())))
print(a)
print(any(a==0))

[1 2 3 4 0]
True


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [2]:
import numpy as np
a=np.array([0]*10)
b=np.array([1]*10)
c=np.array([5]*10)
print(a,b,c)
    

[0 0 0 0 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1 1] [5 5 5 5 5 5 5 5 5 5]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [3]:
import numpy as np
a=np.random.randn(15)
print(a)

[-0.03084661 -0.30227619  1.07223131 -0.64001384 -0.34406045  1.10751169
 -1.27156775 -0.43782711 -2.41150756  1.76452518  0.34743679  0.58330869
 -0.40191109  1.02470513 -0.7356297 ]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [6]:
import numpy as np
m = 200
std = 7
a = np.random.normal(m, std, (8, 5))
print(a)

[[197.99546058 210.96311959 196.23402156 202.23964758 203.9226654 ]
 [192.71200499 199.70866157 199.26154027 192.09914007 199.76797983]
 [202.05552985 189.34213109 195.99828725 197.21689774 200.1728158 ]
 [197.14024599 196.28887574 195.5516958  189.44944344 194.69150223]
 [198.47152879 200.09502007 199.30919646 198.46066791 191.0119534 ]
 [195.82729879 200.25623765 206.59113382 200.5537102  192.83730138]
 [185.82981174 200.90816256 199.65941879 196.07716886 188.85327226]
 [196.32780108 194.68755135 207.4382431  205.63987429 197.19550209]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [8]:
import numpy as np
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
swapped_array = original_array[:, [3, 1, 2, 0]]
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Swapped Array:
[[ 4  2  3  1]
 [ 8  6  7  5]
 [12 10 11  9]
 [16 14 15 13]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [9]:
import numpy as np
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
reversed_rows = original_array[::-1]
reversed_columns = original_array[:, ::-1]
swapped_array = reversed_rows[:, ::-1]
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Swapped Array:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [11]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res = arr1 * arr2
print(res)

[[ 5 12]
 [21 32]]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [12]:
import numpy as np
values = np.arange(2, 11)
mat = values.reshape(3, 3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [21]:
import numpy as np
r = np.random.rand(3, 3, 3)
print(r)

[[[0.41742547 0.02181609 0.83291539]
  [0.09774561 0.84377275 0.54654973]
  [0.28765095 0.53461106 0.93814954]]

 [[0.05038161 0.89867239 0.45420517]
  [0.34716367 0.65433008 0.58786461]
  [0.63928362 0.51211792 0.07588284]]

 [[0.41174461 0.27694256 0.36054077]
  [0.06480478 0.70963324 0.06484372]
  [0.13355717 0.47673193 0.34348882]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [23]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
flattened_array = array.flatten()
max_value = np.amax(flattened_array)
min_value = np.amin(flattened_array)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Maximum value: 9
Minimum value: 1


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [25]:
n1=np.array([1])
n2=np.array([4])
print("Add:",float(n1+n2))
print("Subtract:",float(n1-n2))
print("Multiply:",float(n1*n2))
print("Divide:",float(n1/n2))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [27]:
n1=np.array([0,1,2,3,4,5,6])
n2=np.array([3])
print(n1**n2)

[  0   1   8  27  64 125 216]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [33]:
n=np.random.randint(1,11)
s=int(input("Enter a random Number from 1 to 10:"))
if n==s:
      print("You Gussed the Correct Number")
else:
      print("you Guessed the wrong number. The random number is:"+str(n))

Enter a random Number from 1 to 10:8
you Guessed the wrong number. The random number is:7


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [35]:
import numpy as np
rows, cols = 5, 5
array = np.zeros((rows, cols))
array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1 
print("array:")
print(array.astype(int))

array:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [36]:
arr=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr=np.append(arr,arr2)
print(arr)

[10 20 30 40 50 60 70 80 90]
